name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-10"

# compatibility_flags = [ "nodejs_compat" ]

 [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZTg5Nzg3ODktNWU2NC00MzUzLTg4MzYtMDk3MGNjYTk2YjZmIiwidGVuYW50X2lkIjoiNDE0NjZlMzg5ZTIxNzRlMGNmMjI5NDNmOGYyNzI2ZmE3NzlhMWU4ZDkzMDk0N2QxMjg4Mzk0MGIyYjk4Njc4YyIsImludGVybmFsX3NlY3JldCI6IjcxODAyYjBkLTg1OTctNDE4Ny1iOTQ5LWRiOGY3ZGIyOTc5ZCJ9.6tngE8FV8W6XkYaewNxx-TPVgNMmff-S2f-WYCsWOHY"
DIRECT_URL="postgresql://testdb_owner:Zvakjog50wXq@ep-sweet-bonus-a10mgewt.ap-southeast-1.aws.neon.tech/palindrome?sslmode=require"
JWT_SECRET="fvbjhdsbcjknds&&&"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1